apiVersion: v1
kind: Service
metadata:
  name: graphical-web-app-service
spec:
  selector:
    app: graphical-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
